### PR TITLE
- Change type of modResource.description to be "text"

### PR DESCRIPTION
**Pull request by bezumkin**
- Change type of modResource.description to be "text" instead of "varchar"
- Small code improvements.

This will allow to use long descriptions and don't wait for MODX 2.7 release

### CODE REVIEW

**Comment by joeke** [comment]
@bezumkin Nice solution Vasily! I did not know you could override the mapping OnMODXInit. Does this have any performance impacts?

**Comment by bezumkin** [comment]
Not at all, MODX loads this map into memory at each load - and we can change it without any impacts.

**Comment by joeke** [comment]
@bezumkin One note: in the description resolver on uninstall you revert the the description back to varchar(191), but modx versions prior to 2.6 had varchar(255). Maybe you could edit it so it gets the original fitting with the current modx version (from the schema perhaps)?

**Comment by bezumkin** [comment]
[It was reduced in 2.6.1](https://github.com/modxcms/revolution/commit/716866281ac677d010c6051026b63a537e1653eb#diff-f032a2068ea0a2229b531a77f448215b), but you right, I can check schema of current site.

**Pull request merged**
